### PR TITLE
Trappist node refactor

### LINKED ISSUE #177: Trappist node refactor
# Trappist node refactor

As it was decided, we will refactor the node build setup, specifically over the `service.rs` + `command.rs` files. In a nutshell we will get rid of the runtime build features `with-stout-runtime` and `with-trappist-runtime` and compile all native runtimes into one and only binary `trappist-collator`.

## Why we are not convinced about the runtime build features?

- The compilation time is the double since the two collators need to be built from scratch for each runtime.
- Having the features `with-stout-runtime` and `with-trappist-runtime`, just makes the code harder to follow and in a way we have abused on them by just duplicating the exact same code but with different build features. Here you have an example: the trappist [start_node_impl](https://github.com/paritytech/trappist/blob/main/node/service/src/lib.rs#L175) and the stout [start_node_impl](https://github.com/paritytech/trappist/blob/main/node/service/src/lib.rs#L349). Another example is how we import the `chain_specs` : https://github.com/paritytech/trappist/blob/main/node/cli/src/command.rs#L65

## Refactor proposal
The proposal is to basically remove runtime build features and merge all the runtimes into one single collator file (`trappist-collator`). Also remove the `cli` and `service` directories and comeback to the `command.rs` and `service.rs` files, matching with the parachain template and common good parachains.

There are some tweaks that need to be done on the service file like for example extending the types for the `start_node_impl` fn as:

```rust
#[sc_tracing::logging::prefix_logs_with("Parachain")]
async fn start_node_impl<RuntimeApi, RB, BIQ, BIC>(
	parachain_config: Configuration,
	polkadot_config: Configuration,
	collator_options: CollatorOptions,
	para_id: ParaId,
	_rpc_ext_builder: RB,
	build_import_queue: BIQ,
	build_consensus: BIC,
	hwbench: Option<sc_sysinfo::HwBench>,
) -> sc_service::error::Result<(TaskManager, Arc<ParachainClient<RuntimeApi>>)>
where
	RuntimeApi: ConstructRuntimeApi<Block, ParachainClient<RuntimeApi>> + Send + Sync + 'static,
	RuntimeApi::RuntimeApi: sp_transaction_pool::runtime_api::TaggedTransactionQueue<Block>
		+ sp_api::Metadata<Block>
		+ sp_session::SessionKeys<Block>
		+ sp_api::ApiExt<
			Block,
			StateBackend = sc_client_api::StateBackendFor<ParachainBackend, Block>,
		> + sp_offchain::OffchainWorkerApi<Block>
		+ sp_block_builder::BlockBuilder<Block>
		+ cumulus_primitives_core::CollectCollationInfo<Block>
		+ pallet_transaction_payment_rpc::TransactionPaymentRuntimeApi<Block, Balance>
		+ frame_rpc_system::AccountNonceApi<Block, AccountId, Nonce>,
	sc_client_api::StateBackendFor<ParachainBackend, Block>: sp_api::StateBackend<BlakeTwo256>,
	RB: Fn(Arc<ParachainClient<RuntimeApi>>) -> Result<jsonrpsee::RpcModule<()>, sc_service::Error>,
	BIQ: FnOnce(
		Arc<ParachainClient<RuntimeApi>>,
		ParachainBlockImport<RuntimeApi>,
		&Configuration,
		Option<TelemetryHandle>,
		&TaskManager,
	) -> Result<
		sc_consensus::DefaultImportQueue<Block, ParachainClient<RuntimeApi>>,
		sc_service::Error,
	>,
	BIC: FnOnce(
		Arc<ParachainClient<RuntimeApi>>,
		ParachainBlockImport<RuntimeApi>,
		Option<&Registry>,
		Option<TelemetryHandle>,
		&TaskManager,
		Arc<dyn RelayChainInterface>,
		Arc<sc_transaction_pool::FullPool<Block, ParachainClient<RuntimeApi>>>,
		Arc<SyncingService<Block>>,
		SyncCryptoStorePtr,
		bool,
	) -> Result<Box<dyn ParachainConsensus<Block>>, sc_service::Error>,
{ 
    ...
```

Also the `command.rs` need some additional code like

```rust
#[derive(Debug, PartialEq, Default)]
enum Runtime {
	/// This is the default runtime (actually based on rococo)
	#[default]
	Default,
	Shell,
	Seedling,
	Statemint,
    ...
}

macro_rules! construct_benchmark_partials {
	($config:expr, |$partials:ident| $code:expr) => {
		match $config.chain_spec.runtime() {
			Runtime::Statemine => {
				let $partials = new_partial::<statemine_runtime::RuntimeApi, _>(
					&$config,
					crate::service::aura_build_import_queue::<_, AuraId>,
				)?;
				$code
			},
			Runtime::Westmint => {
				let $partials = new_partial::<westmint_runtime::RuntimeApi, _>(
					&$config,
					crate::service::aura_build_import_queue::<_, AuraId>,
				)?;
				$code
			},
...

macro_rules! construct_async_run {
    	(|$components:ident, $cli:ident, $cmd:ident, $config:ident| $( $code:tt )* ) => {{
		let runner = $cli.create_runner($cmd)?;
		match runner.config().chain_spec.runtime() {
			Runtime::Westmint => {
				runner.async_run(|$config| {
					let $components = new_partial::<westmint_runtime::RuntimeApi, _>(
						&$config,
						crate::service::aura_build_import_queue::<_, AuraId>,
					)?;
					let task_manager = $components.task_manager;
					{ $( $code )* }.map(|v| (v, task_manager))
				})
			},
			Runtime::Statemine => {
				runner.async_run(|$config| {
					let $components = new_partial::<statemine_runtime::RuntimeApi, _>(
						&$config,
						crate::service::aura_build_import_queue::<_, AuraId>,
					)?;
					let task_manager = $components.task_manager;
					{ $( $code )* }.map(|v| (v, task_manager))
				})
			},

```

### PR DESCRIPTION
**Pull request by hbulgarini**
# Trappist Node Refactor

This PR constitutes a complete node refactor for the Trappist project. The motivation behind this change has been deliberated and documented in issue #177.

## General

- Introduces a clear directory structure similar to the Cumulus project.
- Consolidates to a single node binary that contains both `trappist` and `stout` runtimes, now named `trappist-node`. The binary was renamed from `trappist-collator` to `trappist-node` in line with the more accurate description of it as _a node executing the collator function_.

## `service.rs`

The functions `new_partial`, `start_node_impl`, and `start_aura_node` now include generics to process different runtimes, thereby avoiding code duplication.

## `command.rs`

- The macros `construct_benchmark_partials` and `construct_async_run` have been added/modified to supply the corresponding runtime API types.

## Chain Specifications

A substantial amount of repetitive code has now been moved to `node/chain_specs/mod.rs`.

## Limitations

For simplicity's sake, we assume that the setup of runtime APIs is identical for Trappist and Stout runtimes. Should there be a disparity between the two, the service file would need to be modified in a way that allows for the processing of different service functions, since the RuntimeApi types will differ.

Closes #177.

### CODE REVIEW

**Review by stiiifff — APPROVED** [review]

File: node/src/service.rs [hunk 1]
```diff
@@ -0,0 +1,752 @@
...
+		select_chain: (),
+		other: (block_import, telemetry, telemetry_worker_handle),
+	};
+
+	Ok(params)
+}
+
+/// Start a node with the given parachain `Configuration` and relay chain `Configuration`.
+///
+/// This is the actual implementation that is abstract over the executor and the runtime api.
```
Comment (valentinfernandez1) [inline node/src/service.rs:218]: After reading it though it looks pretty good to me. 

Could you maybe add a few more comments here indicating how the generics parameters allow this to make this extensible, it will help a lot whenever we have to go back to this code in the future. 

And if you could also link the reference code that you use as a guide in this PR in a comment that would help a lot for backporting this code to v0.9.40 later.
